= Darkness, Darkness
Robert Plant

[verse]
____
Darkness, Darkness, be my pillow, 
Take my head and let me sleep
In the coolness of your shadow, 
In the silence of your deep

Darkness, darkness, hide my yearning, 
For the things I cannot see
Keep my mind from constant turning, 
To the things I cannot be

Darkness, darkness, be my blanket, 
Cover me with the endless night
Take away the pain of knowing, 
Fill the emptiness with light
Emptiness with light now

Darkness, darkness, long and lonesome, 
Is the day that brings me here
I have felt the edge of sadness, 
I have known the depths of fear

Darkness, darkness, be my blanket, 
Cover me with the endless night
Take away this pain of knowing, 
Fill this emptiness with light now
Emptiness with light now

Darkness, darkness, be my blanket, 
Cover me with the endless night
Take away this pain of knowing, 
Fill this emptiness with light now
Oh with light now.

Darkness, Darkness, be my pillow, 
Take my head and let me sleep
In the coolness of your shadow, 
In the silence of your deep
In the silence of your deep
In the - oh oh yeah
In the summer baby
come on come on come on baby... 
____

http://www.azlyrics.com/lyrics/robertplant/darknessdarkness.html
