= Music of Ancient Greece
Christodulos Halaris

[hardbreaks]
Already in the 3rd millennium B.C., in the prime of the Aegean civilization,the Greeks use musical instruments, whose technological perfection was famous at the time.
This is evidenced by findings such as the figurine known as the Keros harpist (2.800 BC) and many others. The instruments prove the existence of musical practice. But what leads to the necessity of its existence!
In a few words, we would say: 
The wish for a good year and the wish to approach Divinity. Any effort of chronological determination of the birth of the phenomenon of music would be pure utopia.
However, we may say that it coincides with the realization by man of his dependence on the elements of nature, the fertility of earth and the individual conditions leading to it.
However, fertility presupposes the erotic act. The drops of rain are the sperm of heaven. Aeschylus, in an extract from a lost tragedy teaches us that:
"Divine heaven seeks to unite with / earth, which in its turn feels / the erotic desire to sleep with him. / And from heaven's love, / the raindrops, falling on the soil / made the Earth fertile; and she gives birth / for man's sake to the herds / and Demeter's gifts, the trees / gave blossom by the freshness of marriage.
For all this the reason was the divine union.
Vegetation is connected to the resurrection of the seed from the dead. The seed means for primitive man the end of the cycle of life. The dead plant is resurrected if life that is enclosed in the sphere of the seed is driven back to light. The Mother Coddess, Cotyto of the Thracians, Pluto, identical to the Wealth (of the earth) and the dead ancestors are the forces that define the destiny of the seed that is deposed in the soil. Primitive man, being unable to intervene practically in the favourable evolution of the sowing vegetation process resorts to prayer to the good deities and analogic magic.
The more unanimous and simultaneous the expression of the wish of the social group during invocation, the more chances there are for favourable results.
However simultaneous speech presupposes some mutually accepted rules. This gives birth to the need to separate the text recited in metrical periods.
The same text is recited by all, beginning and ending at the same time. This may have given birth to rhythmic recitation.
if those praying give emphasis to their requests by their motion - driven by the rhythm of ther speech, we have dance. When the speech is expressed with the voice placed at a tonic height that little by little begins to vary and evolve, then we have melody (music).
Primitive man invoked the good demons (deities) that determined his survival by speech, rhythm dance, music and even with the mimic representtion of the act (e.g. sowing) and the resuit desired (e.g. vegetation - fruition).
Odes and analogic magic were the first means of intervention invented by man.
If the work of priests was sacrifice and the work of soothsayers was to interpret oracles, the work of every man, individually and collectively, was to approach divinity.
The essential method of approaching divinity was sacred mania. We do not know since when, bur certainly long before the prevalence of the cult of Dionysus, man believed that purification of "every curse" and every mental and physical illness could he achieved if the body was provisionally inhabited by a good spirit. The spirit was mainly invoked through the use of the appropriate music, and often with the help of the mask of the god, whom the believer asked to understand him.
It seems that koryvantism was a kind of manic ecstatic cult. It is mentioned by Plate as very widespread in Athens in the 4th century BC. It is mentioned even beiore that time by Aristophanes and two centuries earlier by Alkman who points out that ecstasy was created with the help of the phrygian pipe. The koryvantes, spirits connected to the cult of the goddess-mother possessed the believers who followed her orgies. Such orgies of the Thracian mother-goddess Cotyto are described in an extract by a tragedy by Aeschylus:

[verse]
____
An occult company approaches
following Cotyto's orgies
and her divine ceremonies.
Pipes (flutes) rounded from the turn
sound slowly, deeply
with deep cries of wild mania.
Cymbals sound, shrieks and invisible voices are heard everywhere. 
like mad bulls. 
The beating of the drum
spread like underground echoes 
filling you with terror.
____

[hardbreaks]
Ecstatic dance is a manifestation of koryvantism. According to Plato the koryvantiots dance in mania. Strabo characterizes them dancers possessed by demons and points out that the verb «koryvantian» denotes people frenitically moving.
The method of ecstasy and sacred magic that leads man to close communication with divinity was inherited by the cult of Dionysus from a preexisting religious practice.
The connertion made by Plate between artistic inspiration, ecstatic mania and sacred mania is extremely interesting. in "ton" in the chapter concerning poetic inspiration he writes: the Muse makes poets divine and since there are also other receivers of inspiration a chain is created for all good poets compose threin beautiful peoms nor by the power of art,but because they are possessed by divinity.
The same is also the case with lyrical poets. But the Karyvantiots dance without having their senses, and so lyric poets are not in possession of reason when they compose their beautiful melodies; by putting their foot in harmony and rhythm they become bacchi and are possessed by divinity. As the Bacchantes draw honey and milk from the rivers when possessed by the demon and not when they are in possession of their senses, the soul of the poets behaves in the same way...
One poet is raised by one Muse and another by another - and we say that he is possessed by divinity because he really is in the muses possession and from the first links of poets hang others who also draw their inspiration, sometimes from Orpheus, sometimes from Mousaeus and mast often from Homer. And you, lon,are one of those who are possessed by Homer and when someone recites verses from another poet, you sleep and do not know what to say. And what you say about Homer you do not say it through art or knowledge but through "divine destiny" and possession by the demon, like those who impersonate the Koryvantes and feel deeply only the tune that belongs to the god by whom they are possessed and with that tune they draw manv dancing shapes and say many words, while they remain indifferent to other tunes"
This text by Plate gives a very clear image of the views of the people of his time about the relationship of music to the contact with divinity but also about the necessary condition of relationship to divinity or possession by divinity for inspiration in artistic creation.
Thus one can understand why much later the Neoplatonians and the Neopythagorians still held the view that the artist is the medium that is able through his art to reproduce reflections of divine harmony.
However, the text that mentions Homer, the supreme art creator, as a demon who is in a position to possess, or inspire mortals, alludes to the capacity of art to lead the human being to the highest degrees of knowledge. As it is clearly mentioned in many texts man may climb one by one the steps to perfection through music. He first becomes erotic, then a musician and finally aphilosopher.
The relationship between divine mania - artistic creation and music (as one of the artistic expressions) and possession by divinity (divine mania) - music is clearly retroactive. The view that creation presupposes possession by divinity gives a particular role to the artist within the community that he is invited to serve an'd creates confusion between the meaning of collective (wirhin the framework of artistic creation) and purely personal. How personal can a creation that is only a mirror reflection of the heavenly or the divine and which manifests itself through divine intervetion be? To what extent is a man whose creation in essence dictated by divinity a creator?
Even the possibility of a first order artist, as we would say and as it appears from Plate's text to act as a medium, creates an obligation for him, placing him as a link in the hyman chain, to complete the chain of communication with the surpassable through divine inspiration and his divine work.
We can thus understand why all ancient melodies. action and dances that have been preserved to this day as literary and artistic references and that should be collective creation by nature are often attributed (by tradition) to a particular person, without this fact detracting in any, way from the importance of their function.
In the opinion of the ancient Greeks, the conscious artistic act seems to originate from the imaginary mimic representation of the cult behaviour of the ideal company of Dionysus. Ecstatic mania, the dithyrambus, the choral song of cult in honour of Dionysus, as a means and carrier for approach will lead to the creation of tragedy and satyric drama.
The phallic Dionysian processions, in the opinion of most scholars, will give the impetus for the creation of comedy. Arisloteles in his Poetics claims that tragedy offers purification through "mercy and lear" This appears to be also the role and the reason for the existence of any form of art, through the imitation of divinity.

== Pindar's First Pythionic Hymn

The most ancient specimen of Greek music that has survived until our time should 
be considered to be the work published by the lesuite monk Athanasios Kircher in 
his work Musurgia Universalis (Rome 1650 vol. 1 541-42) presenting it as an 
extract from Pindar's first Pythionic. The monk claimed to have copied the 
melody from a manuscript discoverd in the library of a monastery near Messina. 

The manuscript mentioned by Kircher was never found. Thus most scholars believe 
that the extract from the first Pythionic Hymn is fake. Since the possibility of 
theft or destruction of the manuscript was not taken into consideration, we 
propose it to you in its first execution.

== 1st Chorus from Euripides Tragedy "Orestes" 

Undoubtedly the oldest specimen of ancient Creek music discovered to this day is 
an extract from the first stasimon of the tragedy "Orestes" by Euripides. 
As was usually the case, the poet also composed the music of the tragedy which 
he taught around 408 B.C. The extract that has been preserved was discovered in, 
1892 in a papyrus in Archduke Rainer's library and was transcribed by Carl 
Wessely (Mitteilungen aus der Sammlung der Papyri Erzherzog Rainer 1892).

== Second Delphic Hymn

The two hymns to Apollo that became known as "Delphic hymns" were discovered by 
the French Archaeological School in Athens in 1893. They were found engraved on 
the hoard of the Athenians at Delphi. 
They are two paeans dated by Theodor Reinach ca. 138 B.C. for the first and ca. 
128 BC for the second. Reinach also transcribed them into modern music 
semantics. His work was published with comments by Henri Well in the Bulletin de 
Correspondance Hellenique, (The first Delphic Hymn in 1893 and the second in 
1894).These two works are certainly the most extensive specimens of ancient 
Creek music preserved until today. In the execution proposed by us, the missi ng 
(unreadable) parts of the musical text were cornpleted by Christodoulos Halaris. 
The work is attributed to the Athenian Limenios.
