= Радио Аэростат. Глава XV
:toc: left

> link:aerostat.html[<Home>]
> link:toc.html[<Contents>]
> link:lyrics.html[<Lyrics>]

== 13 ноября 2011 - 29 апреля 2012

<http://old.aquarium.ru/misc/aerostat/index15.html>

++++
<style>
h2 {
  background-color: #FFC0CB;
}
h3 {
  clear: both;
}
</style>
++++

=== Белтайн, 29 апреля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat363.html>

[%hardbreaks]
Pennou Skoulm - A Dix Heures A St Vincent
Cormack Breatnach - Christmastime In Ashland
Iron Horse - The Burning Of Auchindoun
Moving Hearts - Tribute To Peadar O'Donne
Jim Reid - Rohallion
Battlefield Band - Mo Ghleannan Taobh
Kan - Coriolis
Jim Reid - Wild Geese
Breabach - Lochaber No More

++++
<br clear="both">
++++

=== Свадебные песни, 22 апреля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat362.html>

[%hardbreaks]
Mary Hopkin - The Honeymoon Song
Cat Stevens - Two Fine People
Swingle Singers - Aria
Cotton Mather - Monterrey Honey
Tom Petty - Wildflowers
Silly Wizard - Banks Of The Bann
Rachmaninov - Concerto #2, Part 2, Adagio
Paul McCartney - No More Lonely Nights 

++++
<br clear="both">
++++

=== Пасха, 15 апреля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat361.html>

[%hardbreaks]
Beatles - Hello Goodbye
Roland Godard - Elisa
Гайворонский - Серебро Господа Моего
Clannad - Trathnona Love
Аквариум - Цветы На Огороде
Leonard Cohen - The Captain
Fleetwood Mac - Albatross
Arthur Brown - Love Is The Spirit 

++++
<br clear="both">
++++

=== The Monkees, 8 апреля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat360.html>

[%hardbreaks]
The Monkees - Last Train To Clarksville
The Monkees - Theme From The Monkees
The Monkees - A Little Bit Me A Little Bit You
The Monkees - Take A Giant Step
The Monkees - Mary Mary
The Monkees - This Just Doesn't Seem To Be My Day
The Monkees - When Love Comes Knocking At Your Door
The Monkees - Love Is Only Sleeping
The Monkees - Randy Scouse Git
The Monkees - I'm A Believer
The Monkees - Pleasant Valley Sunday
The Monkees - Words
The Monkees - Daydream Believer

++++
<br clear="both">
++++

=== Нововышедшее, 1 апреля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat359.html>

[%hardbreaks]
Storl - Sonata #5
Paul McCartney - It's Only A Paper Moon
Guided By Voices - Doughnut For A Snowman
Public Image Ltd. - One Drop
Magnetic Fields - I'd Go Anywhere With Hug
Leonard Cohen - Going Home
Mouse On Mars - They Know Your Name
KAN - Eva
Doors - She Smells So Nice
Cotton Mather - The Gold Gone Days
Sinead O'Connor - Wolf Is Getting Married
Paul McCartney - I'm Gonna Sit Right Down

++++
<br clear="both">
++++

=== Харри Парч и все-все-все, 25 марта 2012

<http://old.aquarium.ru/misc/aerostat/aerostat358.html>

[%hardbreaks]
Man Man - Steak Knifes
Horrible Crowes - Mary Ann
Jesca Hoop - City Bird
Sinn Sisamouth - Mou Pei Na
Malikah & Zoog - Intikhabeit 2009
Harry Partch - Ring Around The World Phase 1
Beck - Harry Partch Mm2 Mst
Beatles - I'll Follow The Sun
T.Rex - Lofty Skies

++++
<br clear="both">
++++

=== "Parsley, Sage, Rosemary & Thyme", 18 марта 2012

<http://old.aquarium.ru/misc/aerostat/aerostat357.html>

[%hardbreaks]
Simon & Garfunkel - Fakin'It
Simon & Garfunkel - Scarborough Fair/Canticle
Simon & Garfunkel - The Big Bright Green Pleasure Machine
Simon & Garfunkel - The Dangling Conversation
Simon & Garfunkel - For Emily, Whenever I May Find Her
Simon & Garfunkel - A Poem On The Underground Wall
Simon & Garfunkel - Bookends
Simon & Garfunkel - Save The Life Of My Child
Simon & Garfunkel - America
Simon & Garfunkel - Overs
Simon & Garfunkel - Old Friends
Simon & Garfunkel - Bookends (reprise)
Simon & Garfunkel - Hazy Shade Of Winter
Simon & Garfunkel - Mrs. Robinson
Simon & Garfunkel - Flowers Never Bend With A Rainfall

++++
<br clear="both">
++++

=== А это кто такие?, 11 марта 2012

<http://old.aquarium.ru/misc/aerostat/aerostat356.html>

[%hardbreaks]
Jukebox The Ghost - Schizophrenia
Bishop Allen - Click Click Click Click
Stephen Fretwell - Bad Bad Me Bad Bad You
Dark Ocean Colors - Crashing The Sky
Pillbugs - Glad To Be Alive
John Stammers - Idle I'm
Cornershop - Judy Sucks A Lemon For Breakfast
Nada Surf - When I Was Young
Patty Griffin - Goodbye

++++
<br clear="both">
++++

=== Slade, 4 марта 2012

<http://old.aquarium.ru/misc/aerostat/aerostat355.html>

[%hardbreaks]
Slade - Cum On Feel The Noise
Slade - When The Lights Are Out
Slade - Find Yourself A Rainbow
Slade - Get Down And Get With It
Slade - Coz I Luv You
Slade - So Far So Good
Slade - Do We Still Do It?
Slade - How Does It Feel
Slade - Look Wot You Dun
Slade - Miles Out To Sea
Slade - Summer Song (Wishing You Were Here)

++++
<br clear="both">
++++

=== Калипсо и другие, 26 февраля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat354.html>

[%hardbreaks]
Bob Marley - Roots Rock Reggae
Lord Shorty - Kim
Lovey's Trinidad String Band - Mango Vert
Lord Composer - Rum & Coca Cola
Septeto Matamoros - Oye Mi Coro
Bob Marley - Rastaman Chant
Byron Lee & Dragonaires - Jamaica Ska
Harry J Allstars - Liquidator
Desmond Dekker - 007
Specials - Monkey Man
Lee Scratch Perry - Dreadlocks In Moonlight

++++
<br clear="both">
++++

=== Меланхолия, 19 февраля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat353.html>

[%hardbreaks]
Beck - Everybody Gotta Learn Sometime
Robert Wyatt - Memories
Jethro Tull - Rosa On The Factory Floor
Котов-Старостин-Волков - Псалом No.1
Weepies - Hummingbird
Pete Coe - Wait Till The Clouds Roll By
King Crimson - Fallen Angel
Tom Waits - New Year's Eve
Gene Clark - One In A Hundred

++++
<br clear="both">
++++

=== Haydn, 12 февраля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat352.html>

[%hardbreaks]
Haydn - Concert For Harpsichord And Orchestra.1
Haydn - Trumpet Concerto. Andante
Haydn - Cello Concerto #2. Adagio
Haydn - Symphony #82 "The Bear", Allegretto
Haydn - Symphony #83. 4. Finale
Haydn - Rondo Presto
Haydn - Quartet For Strings "Emperor"
Haydn - Symphony #84. 4. Finale

++++
<br clear="both">
++++

=== Gryphon Prog, 5 февраля 2012

<http://old.aquarium.ru/misc/aerostat/aerostat351.html>

[%hardbreaks]
United States Of America - Cloud Song
Moody Blues - Tuesday Afternoon
Schoenberg - Transfigured Night
Gentle Giant - Isn't It Quiet And Cold?
Camel - Spirit Of The Water
Gryphon - Tea Wrecks
Gryphon - Ploughboy's Dream
Gryphon - Pastime With Good Company
Gryphon - Kemp's Jig
Gryphon - Unquiet Grave
Emerson Lake & Palmer - The Sage

++++
<br clear="both">
++++

=== Imbolc 2012, 29 января 2012

<http://old.aquarium.ru/misc/aerostat/aerostat350.html>

[%hardbreaks]
Chieftains - Hunter's Purse
Young Dubliners - Foggy Dew
Karan Casey - The Flower Of Finae
Capercaille - Turas An Anraidh
Chieftains - Carrickfergus
Plethyn - Ffarwel I Blwy Llangwer
Alan Stivell - Marv Pontkellec
Milladoiro - A Bruha
Young Dubliners - Follow Me Up To Carlow
Rick Sanders - The Rose Hip
Danu - County Down

++++
<br clear="both">
++++

=== Охота К Перемене Мест, 22 января 2012

<http://old.aquarium.ru/misc/aerostat/aerostat349.html>

[%hardbreaks]
Free - Travellin' In Style
Traveling Wilburys - Like A Ship
Traffic - Hope I Never Find Me There
Grateful Dead - Truckin'
Michael McGoldrick - The History Man
Pugwash - Here We Go 'round Again
Tom Petty - Time To Move On
High Llamas - Wander, Jack Wander
Electric Light Orchestra - Down Home Town
Paul McCartney - Wanderlust

++++
<br clear="both">
++++

=== Совсем Новые Песни, 15 января 2012

<http://old.aquarium.ru/misc/aerostat/aerostat348.html>

[%hardbreaks]
Paul McCartney - My Valentine
Rolling Stones - So Young
Leonard Cohen - Show Me The Place
Radiohead - Putting Ketchup In The Fridge
Lambchop - If Not I'll Just Die
Black Keys - Dead And Gone
Broken Bells - An Easy Life
Kate Bush - Wild Man
John Wesley Harding - Starbucks 

++++
<br clear="both">
++++

=== Обо Всем Понемногу, 8 января 2012

<http://old.aquarium.ru/misc/aerostat/aerostat347.html>

[%hardbreaks]
Dobet Gnahore - Massacre
Strawbs - Witchwood
Slightly Stoopid - Sweet Honey
Tom Petty - Waiting For Tonight
Atrium Musicae - Premier Hymne Delphique a Apollon
Nickelback - How You Remind Me
Paul Simon - The Vampires
Gerry & The Pacemakers - It's Gonna Be Alright
Bob Marley - One Love
R.E.M. - Why Not Smile 

++++
<br clear="both">
++++

=== С Новым Годом!, 1 января 2012

<http://old.aquarium.ru/misc/aerostat/aerostat346.html>

[%hardbreaks]
Paul McCartney - Uncle Albert
Corbett - Suite in D
Bob Dylan - Forever Young
John Lennon - #9 Dream
George Harrison - Run Of The Mill
Jethro Tull - Ladies
Jeff Lynne - What Would It Take
J.S.Bach - Capriccio B Flat Maj
Cotton Mather - April's Fool
George Harrison - I Got My Mind Set On You

++++
<br clear="both">
++++

=== Happy Christmas!, 25 декабря 2011

<http://old.aquarium.ru/misc/aerostat/aerostat345.html>

[%hardbreaks]
Bing Crosby - I'll Be Home For Christmas
Nat King Cole - Joy To The World
Bert Jansch - In A Bleak Midwinter
Albion Christmas Band - Hark The Herald
Annie Lennox - See Amid The Winter's Snow
Elvis Presley - Santa Bring My Baby Back
Bob Dylan - Do You Hear What I Hear
Leon Redbone - Home For Christmas
Girls Aloud - Not Tonight Santa
Doris Day - Here Comes Santa Claus
Аквариум - Бригадир
John Lennon - Happy Christmas (War Is Over)
Bing Crosby - White Christmas

++++
<br clear="both">
++++

=== Святой Кит, 18 декабря 2011

<http://old.aquarium.ru/misc/aerostat/aerostat344.html>

[%hardbreaks]
Rolling Stones - Sittin' On A Fence
Rolling Stones - Flip The Switch
Rolling Stones - I Am Waiting
Rolling Stones - You Got The Silver
Rolling Stones - Little Red Rooster
Rolling Stones - Sweethearts Together
Rolling Stones - Winter
Rolling Stones - Mixed Emotions
Rolling Stones - 100 Years Ago
Rolling Stones - Happy

++++
<br clear="both">
++++

=== Новая Романтика, 11 декабря 2011

<http://old.aquarium.ru/misc/aerostat/aerostat343.html>

[%hardbreaks]
Ultravox - Dancing With Tears In My Eyes
ABC - The Look Of Love
Classix Nouveau - Because You're Young
Spandau Ballet - Chant #1
Dead Or Alive - You Spin Me Round
Visage - Fade To Grey
Ultravox - Vienna
Duran Duran - The Chauffer
Japan - Cantonese Boy
Кино - Прогулка Романтика
Ultravox - The Hymn

++++
<br clear="both">
++++

=== Duckworth Lewis Method, 4 декабря 2011

<http://old.aquarium.ru/misc/aerostat/aerostat342.html>

[%hardbreaks]
Duckworth Lewis Method - The Coin Toss
Duckworth Lewis Method - The Age Of Revolution
Duckworth Lewis Method - Gentlemen And Players
Duckworth Lewis Method - The Sweet Spot
Duckworth Lewis Method - Jiggery Pokery
Duckworth Lewis Method - Mason On The Boundary
Duckworth Lewis Method - Test Match Special
Duckworth Lewis Method - The Nightwatchman
Duckworth Lewis Method - Flatten The Hay
Duckworth Lewis Method - Meeting Mr. Miandad
Duckworth Lewis Method - The End Of The Over

++++
<br clear="both">
++++

=== Под Радар, 27 ноября 2011

<http://old.aquarium.ru/misc/aerostat/aerostat341.html>

[%hardbreaks]
Pink Floyd - Welcome To The Machine
King Crimson - Moonchild
Cambini - Quintet
T.Rex - Iscariot
Grateful Dead - Crazy Fingers
T.Rex - Rapids
Gonzales - Armellodie
Grasscut - Swallow The Day
Cat Stevens - I Can't Keep It In
Beatles - You Won't See Me 

++++
<br clear="both">
++++

=== Bell X1, 20 ноября 2011

<http://old.aquarium.ru/misc/aerostat/aerostat340.html>

[%hardbreaks]
Bell X1 - In Every Sunflower
Bell X1 - I'll See Your Heart And I'll Raise You Mine
Bell X1 - Just Like Mr. Benn
Damien Rice - The Blower's Daughter
Bell X1 - Snakes And Snakes
Bell X1 - Slowset
Bell X1 - Velcro
Bell X1 - Eve The Apple Of My Eye

++++
<br clear="both">
++++

=== Ваши Заявки, 13 ноября 2011

<http://old.aquarium.ru/misc/aerostat/aerostat339.html>

[%hardbreaks]
Johann Fischer - Suite In C Maj Ouverture
Tame Impala - Lucidity
English Beat - Hands Off She's Mine
Beatles - I Should Have Known Better
Fountains Of Wayne - Hey Julie
Dave Van Ronk - Duncan And Brady
Brad Mehldau - When It Rains
Cream - What A Bringdown
Richard Thompson - Miss Patsy

++++
<br clear="both">
++++

> link:aerostat.html[<Home>]
> link:toc.html[<Contents>]
> link:lyrics.html[<Lyrics>]
